// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvccvjycomkjqnpvbaqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2Y2N2anljb21ranFucHZiYXFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODQ5MDYsImV4cCI6MjA2NzU2MDkwNn0.jMjlYrg5L4AHFK8PPknKpUHzMt8RTNE8NAoxxMW25Fg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});